import type { QRStyle } from './qr-style-types';

export const BUILTIN_PRESETS: QRStyle[] = [
  // --- 1. Quiet & Editorial ---
  {
    id: 'ink',
    name: 'Ink',
    moduleShape: 'classy',
    moduleColor: '#16161A',
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'circle',
    eyeOuterColor: '#16161A',
    eyeInnerColor: '#16161A',
    plateColor: '#F6F3EE',
    plateBorderWidth: 1,
    plateBorderColor: 'rgba(22, 22, 26, 0.08)',
    plateRadius: 20,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#16161A',
    centerElement: { type: 'none', sizePercent: 20, shape: 'rounded-square', hasRing: true, ringColor: '#F6F3EE' },
    layout: 'plaque',
    showCaption: true,
    captionFont: 'Fraunces',
    captionColor: '#F6F3EE',
  },
  {
    id: 'midnight-press',
    name: 'Midnight Press',
    moduleShape: 'square',
    moduleColor: '#0E1B33',
    eyeOuterShape: 'square',
    eyeInnerShape: 'square',
    eyeOuterColor: '#C8A24A',
    eyeInnerColor: '#0E1B33',
    plateColor: '#F4F1EA',
    plateBorderWidth: 1,
    plateBorderColor: '#C8A24A',
    plateRadius: 12,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#0E1B33',
    centerElement: { type: 'none', sizePercent: 20, shape: 'rounded-square', hasRing: true, ringColor: '#F4F1EA' },
    layout: 'hairline',
    showCaption: true,
    captionFont: 'Fraunces',
    captionColor: '#F4F1EA',
  },
  {
    id: 'sunday-linen',
    name: 'Sunday Linen',
    moduleShape: 'rounded',
    moduleColor: '#3A332B',
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'rounded',
    eyeOuterColor: '#3A332B',
    eyeInnerColor: '#8C7765',
    plateColor: '#FBF8F1',
    plateBorderWidth: 1,
    plateBorderColor: '#E3D9C9',
    plateRadius: 22,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#E9E1D3',
    centerElement: { type: 'none', sizePercent: 20, shape: 'circle', hasRing: true, ringColor: '#FBF8F1' },
    layout: 'polaroid',
    showCaption: true,
    captionFont: 'Newsreader',
    captionColor: '#3A332B',
  },
  {
    id: 'paper-pine',
    name: 'Paper & Pine',
    moduleShape: 'square',
    moduleColor: '#1F3A2E',
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'rounded',
    eyeOuterColor: '#1F3A2E',
    eyeInnerColor: '#3D6B57',
    plateColor: '#F7F2E7',
    plateBorderWidth: 1,
    plateBorderColor: 'rgba(31, 58, 46, 0.12)',
    plateRadius: 16,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#1F3A2E',
    centerElement: { type: 'none', sizePercent: 20, shape: 'rounded-square', hasRing: true, ringColor: '#F7F2E7' },
    layout: 'ticket',
    showCaption: true,
    captionFont: 'Cormorant Garamond',
    captionColor: '#F7F2E7',
  },
  {
    id: 'graphite-mono',
    name: 'Graphite Mono',
    moduleShape: 'extra-rounded',
    moduleColor: '#2B2B2B',
    eyeOuterShape: 'circle',
    eyeInnerShape: 'circle',
    eyeOuterColor: '#2B2B2B',
    eyeInnerColor: '#2B2B2B',
    plateColor: '#EDEDED',
    plateBorderWidth: 1,
    plateBorderColor: '#BCBCBC',
    plateRadius: 24,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#CFCFCF',
    centerElement: { type: 'none', sizePercent: 20, shape: 'circle', hasRing: true, ringColor: '#EDEDED' },
    layout: 'hairline',
    showCaption: true,
    captionFont: 'JetBrains Mono',
    captionColor: '#1A1A1A',
  },
  {
    id: 'noir-gold',
    name: 'Noir Gold',
    moduleShape: 'classy',
    moduleColor: '#111111',
    eyeOuterShape: 'square',
    eyeInnerShape: 'circle',
    eyeOuterColor: '#111111',
    eyeInnerColor: '#8A6A1F',
    plateColor: '#FAF6EC',
    plateBorderWidth: 1,
    plateBorderColor: '#C8A24A',
    plateRadius: 14,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#111111',
    centerElement: { type: 'none', sizePercent: 20, shape: 'rounded-square', hasRing: true, ringColor: '#FAF6EC' },
    layout: 'plaque',
    showCaption: true,
    captionFont: 'Bodoni Moda',
    captionColor: '#FAF6EC',
  },

  // --- 2. Warm & Colourful ---
  {
    id: 'terracotta',
    name: 'Terracotta',
    moduleShape: 'rounded',
    moduleColor: '#8A3B22',
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'circle',
    eyeOuterColor: '#C4572F',
    eyeInnerColor: '#8A3B22',
    plateColor: '#FBF4EC',
    plateBorderWidth: 1,
    plateBorderColor: 'rgba(196, 87, 47, 0.2)',
    plateRadius: 20,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#C4572F',
    centerElement: { type: 'none', sizePercent: 20, shape: 'circle', hasRing: true, ringColor: '#FBF4EC' },
    layout: 'tab',
    showCaption: true,
    captionFont: 'Fraunces',
    captionColor: '#FFFFFF',
  },
  {
    id: 'saffron-line',
    name: 'Saffron Line',
    moduleShape: 'square',
    moduleColor: '#1B1B1B',
    eyeOuterShape: 'square',
    eyeInnerShape: 'square',
    eyeOuterColor: '#1B1B1B',
    eyeInnerColor: '#B87400',
    plateColor: '#FFF6DC',
    plateBorderWidth: 2,
    plateBorderColor: '#B87400',
    plateRadius: 10,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#F2B705',
    centerElement: { type: 'none', sizePercent: 20, shape: 'rounded-square', hasRing: true, ringColor: '#FFF6DC' },
    layout: 'hairline',
    showCaption: true,
    captionFont: 'Instrument Sans',
    captionColor: '#1B1B1B',
  },
  {
    id: 'ember',
    name: 'Ember',
    moduleShape: 'rounded',
    moduleColor: '#3A1208',
    moduleGradient: {
      enabled: true,
      type: 'linear',
      angle: 180,
      stops: ['#3A1208', '#B53A12'],
    },
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'rounded',
    eyeOuterColor: '#B53A12',
    eyeInnerColor: '#3A1208',
    plateColor: '#FFF4EA',
    plateBorderWidth: 1,
    plateBorderColor: '#E6A385',
    plateRadius: 20,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#20110C',
    centerElement: { type: 'none', sizePercent: 20, shape: 'circle', hasRing: true, ringColor: '#FFF4EA' },
    layout: 'plaque',
    showCaption: true,
    captionFont: 'Fraunces',
    captionColor: '#FFF4EA',
  },
  {
    id: 'dusk-rose',
    name: 'Dusk Rose',
    moduleShape: 'dots',
    moduleColor: '#5B2A3A',
    moduleGradient: {
      enabled: true,
      type: 'linear',
      angle: 135,
      stops: ['#5B2A3A', '#B24C63'],
    },
    eyeOuterShape: 'circle',
    eyeInnerShape: 'circle',
    eyeOuterColor: '#5B2A3A',
    eyeInnerColor: '#B24C63',
    plateColor: '#FFF5F4',
    plateBorderWidth: 1,
    plateBorderColor: '#DEC1C6',
    plateRadius: 24,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#E9B8B0',
    centerElement: { type: 'none', sizePercent: 20, shape: 'circle', hasRing: true, ringColor: '#FFF5F4' },
    layout: 'polaroid',
    showCaption: true,
    captionFont: 'DM Serif Display',
    captionColor: '#4A1D2B',
  },
  {
    id: 'plum-hours',
    name: 'Plum Hours',
    moduleShape: 'rounded',
    moduleColor: '#3B1F4A',
    moduleGradient: {
      enabled: true,
      type: 'linear',
      angle: 145,
      stops: ['#3B1F4A', '#7A2E5E'],
    },
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'circle',
    eyeOuterColor: '#3B1F4A',
    eyeInnerColor: '#3B1F4A',
    plateColor: '#FAF3F6',
    plateBorderWidth: 1,
    plateBorderColor: 'rgba(59, 31, 74, 0.15)',
    plateRadius: 18,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#2A1236',
    centerElement: { type: 'none', sizePercent: 20, shape: 'circle', hasRing: true, ringColor: '#FAF3F6' },
    layout: 'hairline',
    showCaption: true,
    captionFont: 'Playfair Display',
    captionColor: '#FAF3F6',
  },

  // --- 3. Cool & Fresh ---
  {
    id: 'monsoon',
    name: 'Monsoon',
    moduleShape: 'classy',
    moduleColor: '#0F3D5C',
    moduleGradient: {
      enabled: true,
      type: 'linear',
      angle: 180,
      stops: ['#0F3D5C', '#1F7A8C'],
    },
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'rounded',
    eyeOuterColor: '#0F3D5C',
    eyeInnerColor: '#0F3D5C',
    plateColor: '#F3F8F8',
    plateBorderWidth: 1,
    plateBorderColor: '#BCD4D8',
    plateRadius: 20,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#0F3D5C',
    centerElement: { type: 'none', sizePercent: 20, shape: 'rounded-square', hasRing: true, ringColor: '#F3F8F8' },
    layout: 'ticket',
    showCaption: true,
    captionFont: 'Fraunces',
    captionColor: '#F3F8F8',
  },
  {
    id: 'glacier',
    name: 'Glacier',
    moduleShape: 'rounded',
    moduleColor: '#123C4A',
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'circle',
    eyeOuterColor: '#123C4A',
    eyeInnerColor: '#2A6678',
    plateColor: '#EEF6F8',
    plateBorderWidth: 1,
    plateBorderColor: '#B6D1DA',
    plateRadius: 22,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#CFE3EA',
    centerElement: { type: 'none', sizePercent: 20, shape: 'circle', hasRing: true, ringColor: '#EEF6F8' },
    layout: 'hairline',
    showCaption: true,
    captionFont: 'Instrument Sans',
    captionColor: '#123C4A',
  },
  {
    id: 'sage-room',
    name: 'Sage Room',
    moduleShape: 'dots',
    moduleColor: '#24402F',
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'rounded',
    eyeOuterColor: '#4F7A5A',
    eyeInnerColor: '#24402F',
    plateColor: '#F2F4EC',
    plateBorderWidth: 1,
    plateBorderColor: '#CCD6C2',
    plateRadius: 20,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#DDE5D3',
    centerElement: { type: 'none', sizePercent: 20, shape: 'rounded-square', hasRing: true, ringColor: '#F2F4EC' },
    layout: 'polaroid',
    showCaption: true,
    captionFont: 'Cormorant Garamond',
    captionColor: '#24402F',
  },
  {
    id: 'cobalt-edit',
    name: 'Cobalt Edit',
    moduleShape: 'square',
    moduleColor: '#1738A8',
    eyeOuterShape: 'square',
    eyeInnerShape: 'square',
    eyeOuterColor: '#1738A8',
    eyeInnerColor: '#1738A8',
    plateColor: '#F5F7FF',
    plateBorderWidth: 1,
    plateBorderColor: 'rgba(23, 56, 168, 0.2)',
    plateRadius: 14,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#1738A8',
    centerElement: { type: 'none', sizePercent: 20, shape: 'rounded-square', hasRing: true, ringColor: '#F5F7FF' },
    layout: 'plaque',
    showCaption: true,
    captionFont: 'Space Grotesk',
    captionColor: '#F5F7FF',
  },

  // --- 4. Bolder Social-Profile Style ---
  {
    id: 'afterglow',
    name: 'Afterglow',
    moduleShape: 'dots',
    moduleColor: '#833AB4',
    moduleGradient: {
      enabled: true,
      type: 'linear',
      angle: 135,
      stops: ['#833AB4', '#E1306C'],
    },
    eyeOuterShape: 'circle',
    eyeInnerShape: 'circle',
    eyeOuterColor: '#C13584',
    eyeInnerColor: '#833AB4',
    plateColor: '#FFFFFF',
    plateBorderWidth: 1,
    plateBorderColor: 'rgba(193, 53, 132, 0.2)',
    plateRadius: 26,
    quietZone: 5,
    backdropType: 'gradient',
    backdropColor: '#833AB4',
    backdropGradient: {
      type: 'linear',
      angle: 135,
      stops: ['#833AB4', '#FD1D1D'],
    },
    centerElement: { type: 'none', sizePercent: 20, shape: 'circle', hasRing: true, ringColor: '#FFFFFF' },
    layout: 'story',
    showCaption: true,
    captionFont: 'Syne',
    captionColor: '#FFFFFF',
  },
  {
    id: 'open-sky',
    name: 'Open Sky',
    moduleShape: 'rounded',
    moduleColor: '#0B5CAD',
    moduleGradient: {
      enabled: true,
      type: 'linear',
      angle: 135,
      stops: ['#0B5CAD', '#1B8FD6'],
    },
    eyeOuterShape: 'rounded',
    eyeInnerShape: 'rounded',
    eyeOuterColor: '#0B5CAD',
    eyeInnerColor: '#1B8FD6',
    plateColor: '#FFFFFF',
    plateBorderWidth: 1,
    plateBorderColor: 'rgba(11, 92, 173, 0.15)',
    plateRadius: 24,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: '#2AABEE',
    centerElement: { type: 'photo', sizePercent: 22, shape: 'circle', hasRing: true, ringColor: '#FFFFFF' },
    layout: 'square',
    showCaption: true,
    captionFont: 'Manrope',
    captionColor: '#FFFFFF',
  },
];

export const COLOR_SWATCHES = {
  neutrals: ['#111317', '#22262E', '#3A3F4A', '#505663', '#7E8594', '#EFECE6', '#FFFFFF'],
  earth: ['#8A3B22', '#B85226', '#C4572F', '#A67C52', '#3A332B', '#1F3A2E', '#F7F2E7'],
  jewel: ['#0E1B33', '#1738A8', '#0F3D5C', '#3B1F4A', '#5B2A3A', '#833AB4', '#C8A24A'],
  pastels: ['#F6F3EE', '#FBF8F1', '#FFF4EA', '#FFF5F4', '#FAF3F6', '#EEF6F8', '#F2F4EC'],
  brights: ['#E1306C', '#FD1D1D', '#F2B705', '#2AABEE', '#1B8FD6', '#40916C', '#1738A8'],
};

/**
 * Generates a random but strictly scannable QR style ("Surprise me").
 */
export function generateSurpriseScannableStyle(): QRStyle {
  const shapes: QRStyle['moduleShape'][] = ['rounded', 'classy', 'dots', 'square'];
  const eyes: QRStyle['eyeOuterShape'][] = ['rounded', 'circle', 'square'];
  const layouts: QRStyle['layout'][] = ['hairline', 'plaque', 'tab', 'polaroid'];
  const darkTones = ['#111317', '#16161A', '#0E1B33', '#1F3A2E', '#24402F', '#3B1F4A', '#8A3B22'];
  const lightPlates = ['#FFFFFF', '#F7F5F0', '#FBF8F1', '#FFF4EA', '#F3F8F8'];
  const fonts = ['Fraunces', 'Instrument Sans', 'Newsreader', 'Cormorant Garamond', 'Manrope'];

  const modColor = darkTones[Math.floor(Math.random() * darkTones.length)];
  const plateCol = lightPlates[Math.floor(Math.random() * lightPlates.length)];
  const shape = shapes[Math.floor(Math.random() * shapes.length)];
  const eye = eyes[Math.floor(Math.random() * eyes.length)];
  const layout = layouts[Math.floor(Math.random() * layouts.length)];
  const font = fonts[Math.floor(Math.random() * fonts.length)];

  return {
    id: `custom_${Date.now()}`,
    name: 'Surprise',
    isCustom: true,
    moduleShape: shape,
    moduleColor: modColor,
    eyeOuterShape: eye,
    eyeInnerShape: eye,
    eyeOuterColor: modColor,
    eyeInnerColor: modColor,
    plateColor: plateCol,
    plateBorderWidth: 1,
    plateBorderColor: 'rgba(0,0,0,0.08)',
    plateRadius: 18,
    quietZone: 5,
    backdropType: 'solid',
    backdropColor: modColor,
    centerElement: { type: 'none', sizePercent: 20, shape: 'circle', hasRing: true, ringColor: plateCol },
    layout,
    showCaption: true,
    captionFont: font,
    captionColor: '#FFFFFF',
  };
}
